### ISSUE TITLE
Open-sourcing MTKit

### ISSUE THREAD

**Issue by RoadTrain** [Kromster80/wr_toolkit#13]
Hello @Kromster80 !

I've come across some discussions around open-sourcing MTKit at games.reveur.de.
It seems you've wanted to do it for 5+ years already.
I think, maybe the time has come?

One of the downsides of open-sourcing it (besides that obviously all models become unlocked) is, [I quote](https://games.reveur.de/board/showthread.php?tid=10443&pid=207465#pid207465):
`- Old passwords could be reverse-engineered and become public`

Maybe it's not really a problem if all passwords-related code is removed from MTKit before open-sourcing.

What do you think?

**Comment by Kromster80** [comment]
I have attempted open-sourcing MTKit2 several times now. Every time there were people against that. You can see last attempt at https://www.facebook.com/groups/159946997370363/permalink/3548889861809376/

**Comment by RoadTrain** [comment]
Unfortunately I'm not a member of this group, though I have just sent a join request, so let's see.

I think there's always gonna be people who are against it.
At this point it's just security through obscurity, when there's barely any obscurity -- if a person really wants a model, it's quite easy to unlock it. I suppose you agree with that.

My (philosophical) point of view is that open community is more resilient than a closed one, so I'm naturally in favor of open-sourcing all modding tools.
My personal interest is game modding/research preservation, so I might be biased here.

Anyway, it's your call in the end :-)

**Comment by RoadTrain** [comment]
Yeah, I can see your post, it was in august 2020, so I guess not much has changed since then.

**Comment by RoadTrain** [comment]
@Kromster80 I suppose we can close this issue now that you've open-sourced MTKit2 :)

**Comment by Kromster80** [comment]
@RoadTrain right, thanks for reminder! )
